### PRODUCTS ###
GET http://localhost:3000/products.json
###

GET  http://localhost:3000/products/8.json
###

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Foody Bib",
  "prices": "35",
  "image_url": "https://im.indiatimes.in/media/content/2018/Jun/weirdest_technology_1528369463_725x725.png",
  "description": "Self-obsession just got foody. You’ve put your selfies on Instagram, you’ve saved it as your wallpaper. You’ve even laminated it on your cups. Where do you take it next? That’s right, you take it to your plates. Mail your selfie to Vermont Novelty Toaster Corp, the creators of Selfie Toaster, and they would make a metal plate with the impression. Put in your toaster and you have your face on your toast. A morning of Me, Myself and I."
}

###
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

{
  "name": "Lightsaber"
}

###
DELETE http://localhost:3000/products/10.json

### SUPPLIERS ###

GET http://localhost:3000/suppliers.json
###

GET  http://localhost:3000/suppliers/3.json
###

POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Foody Bib",
  "email": "nope@spamherelots.com",
  "phone_number": "555-555-5555",
}

###
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "name": "PIXAR"
}

###
DELETE http://localhost:3000/suppliers/5.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTc3MzQ1MzJ9.Jmx-RufeYKyqHXHC7WfBsYGSB8kTWc0RzoaWJ5xCAx8
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

###
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTc4MTkxNDh9._lDsaxc11tTm4dP98121rmKcuxNIKmuNUgdTwMSyHig
Content-Type: application/json

{
  "product_id": "20",
  "quantity": "3"
}